### PR TITLE
Only recommend VS Code

### PR DESCRIPTION
**Pull request by samoylenko**
It's free. IDEA Community doesn't have the required NodeJS support, hence removed.

This is an important milestone: yesterday our research demonstrated that I was wrong recommending IDEA Community as it doesn't have the necessary support for NodeJS. WebStorm is not free, so not recommended either.

I will be using both VS Code and IDEA Ultimate

### CODE REVIEW

**Review by radaken — COMMENTED** [review]
I dont use an IDEA but does it really impossible to open an terminal and launch code or import some plugins to fix that?

**Comment by samoylenko** [comment]
> 
> 
> I dont use an IDEA but does it really impossible to open an terminal and launch code or import some plugins to fix that?

Those plugins are only available after purchasing Ultimate. And that's a large set of functionality you don't want to miss out when starting with Node. But of course the choice is yours, why not try both, and try answering this question yourself a bit later?

**Comment by samoylenko** [comment]
@radaken did you want to continue discussing this, or is it ok to merge?

**Review by radaken — CHANGES_REQUESTED** [review]
yes, I think IDEA can stay as instrument that we use, but vscode become highly-recommended (also checks request review radiobutton)

**Comment by samoylenko** [comment]
> 
> 
> yes, I think IDEA can stay as instrument that we use, but vscode become highly-recommended (also checks request review radiobutton)

The radiobutton you've chose requires me to make some changes, but not sure what is that you wanted me to change - the way I read it, you're ok with leaving VS Code and removing IDEA, right?

image

**Review by radaken — APPROVED** [review]
I want to say that IDEA can stay as additional instrument and vscode had been become highly-recommended tool but now I found my comments confusing, so, I agree with you, IDEA must been deleted from this list

**Pull request merged**
